name: Do stuff
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    environment: lllll
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v6.0.0
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: main
          path: main
      - name: Checkout 2
        uses: actions/checkout@v6
        with:
          ref: prod
          path: prod
      - name: Run node script
        run: node main/build.js
      - name: Deploy to AwardSpace FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: f33-preview.awardspace.net
          username: 4649070_DN4xd8rslY
          password: ${{ secrets.PWD }}
